### ISSUE TITLE
Package is not installable through «pip» command.

### ISSUE THREAD

**Issue by richin13** [dreadpirate15/yact#11]
It would be nice if this package could be installed with pip command
I searched it as yact and didn't find anything.

**Comment by richin13** [comment]
Nevermind, I found it.
It weird because I [searched](https://pypi.python.org/pypi?%3Aaction=search&term=yact&submit=search) and it was not listed.

**Comment by dreadpirate15** [comment]
@richin13 That's odd! I'll verify that it's searchable on pypi. I was able to install as a dependency of some other applications by adding yact to my requirements.txt/setup.py and install directly, so must be some sort of search index that is missing.

**Comment by dreadpirate15** [comment]
https://bitbucket.org/pypa/pypi/issues/326/some-packages-not-showing-up-when

**Comment by richin13** [comment]
Yes, **pip install yact** works smooth but Pypi website is not showing it in search results. 
That's a pretty old issue affecting a lot of people, included you and they haven't patched yet.
Anyway I was able to install yact, thanks for the great lib, is really useful

**Comment by dreadpirate15** [comment]
Glad you find it useful, hope the folks at PyPi get to the bottom of this
issue :/
